name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: terraform
  ROLE_ARN: arn:aws:iam::596122389379:role/github-actions-role

jobs:

  # =========================
  # 1️⃣ Terraform PLAN
  # =========================
  terraform-plan:
    runs-on: ubuntu-latest

    outputs:
      plan-status: ${{ steps.plan.outcome }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Lambda Code
        run: |
          cd terraform/lambda-code
          zip lambda.zip app.py

      # 🔐 Global Authentication
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

  # ==========================
  # 2️⃣ Terraform APPLY
  # ==========================
  terraform-apply:
    needs: terraform-plan   # 👈 depends on plan
    if: needs.terraform-plan.result == 'success'   # 👈 only run if plan success
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Lambda Code
        run: |
          cd terraform/lambda-code
          zip lambda.zip app.py

      # 🔐 Reuse Authentication
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve -input=false 
      #   working-directory: ${{ env.TF_WORKING_DIR }}