name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_WORKING_DIR: terraform

jobs:

  # =========================
  # 1️⃣ Terraform PLAN (PR)
  # =========================
  terraform-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::596122389379:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -input=false -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}

  # =========================
  # 2️⃣ Terraform APPLY (Push)
  # =========================
  terraform-apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    environment:
      name: dev   # You can add approval in GitHub settings

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::596122389379:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}